// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetAPI.Models;

namespace dotnetAPI.Migrations
{
    [DbContext(typeof(SitDbContext))]
    [Migration("20190511041652_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnetAPI.Models.Api", b =>
                {
                    b.Property<int>("APIId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasMaxLength(500);

                    b.HasKey("APIId");

                    b.ToTable("API");
                });

            modelBuilder.Entity("dotnetAPI.Models.Verb", b =>
                {
                    b.Property<int>("VerbId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("APIId");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Parameters")
                        .HasMaxLength(500);

                    b.HasKey("VerbId");

                    b.HasIndex("APIId");

                    b.ToTable("Verb");
                });

            modelBuilder.Entity("dotnetAPI.Models.Verb", b =>
                {
                    b.HasOne("dotnetAPI.Models.Api")
                        .WithMany("Verbs")
                        .HasForeignKey("APIId");
                });
#pragma warning restore 612, 618
        }
    }
}
